.PHONY: clean All

All:
	@echo "----------Building project:[ StackUsingLinkedList - Debug ]----------"
	@cd "StackUsingLinkedList" && "$(MAKE)" -f  "StackUsingLinkedList.mk"
clean:
	@echo "----------Cleaning project:[ StackUsingLinkedList - Debug ]----------"
	@cd "StackUsingLinkedList" && "$(MAKE)" -f  "StackUsingLinkedList.mk" clean
